name: ascom
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#--------------------  PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

# Packages utilitaires
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1   
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.8
  smooth_page_indicator: ^1.1.0
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # Gestion de l'état
  get: ^4.6.6
  get_storage: ^2.1.1

  # Spécifique au produit
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_auth_platform_interface: ^7.0.9
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1


#-------------------- ./ FIN DES PACKAGES ----------------------#


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true 

  #--------------------  ASSETS LOCAL ----------------------#
  assets:
      - assets/logos/
      - assets/icons/brands/
      - assets/icons/categories/
      - assets/icons/payment_methods/
      - assets/images/
      - assets/images/banners/
      - assets/images/animations/
      - assets/images/on_boarding_images/
      - assets/images/products/
      - assets/images/user/
      - assets/images/reviews/

  #--------------------  FONTS LOCAL ----------------------#
  fonts:
      - family: Poppins
        fonts:
            - asset: assets/fonts/Poppins-Light.ttf
              weight: 300
            - asset: assets/fonts/Poppins-Regular.ttf
              weight: 400
            - asset: assets/fonts/Poppins-Italic.ttf
              style: italic
            - asset: assets/fonts/Poppins-Medium.ttf
              weight: 500
            - asset: assets/fonts/Poppins-MediumItalic.ttf
              weight: 500 
              style: italic
            - asset: assets/fonts/Poppins-SemiBold.ttf
              weight: 600 
            - asset: assets/fonts/Poppins-Bold.ttf
              weight: 800        
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
